### ISSUE TITLE
v4.0.3 breaks with Vite: missing "./dist/esm/preset/addDecorator.js"

### ISSUE THREAD

**Issue by ponchique** [rbardini/storybook-addon-paddings#35]
Hey @rbardini,

Thank you for the great add-on.

I tried to install `v4.0.3` but the run was failing with this error:

`12:35:48 PM [vite] Internal server error: Missing "./dist/esm/preset/addDecorator.js" export in "storybook-addon-paddings" package`

As a solution, I had to downgrade to `v4.0.0`

You may be interested in this.

Thank you.

**Comment by tobystokes** [comment]
I suspect this is the same issue - general Storybook v7.0 compatibility - looks like [addDecorator](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#dropped-support-for-addon-actions-adddecorators) does not need to be applied any more.

**Comment by rbardini** [comment]
Seems related to https://github.com/rbardini/storybook-addon-playroom/issues/38. I'll try to release a new major version supporting Storybook 7.0 sometime next week, and hopefully this issue will go away with it 🤞

**Comment by tobystokes** [comment]
Can confirm all is working sweet again with storybook 7 and vite builder, thanks!
