### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [rbardini/storybook-addon-paddings#42]
Hey @rbardini! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by kwickramasekara** [comment]
Not seeing the icon after upgrading to Storybook 8:

![image](https://github.com/rbardini/storybook-addon-paddings/assets/6528584/1c692d59-7c5e-47ec-a14a-ececea47b9a8)

Console warning:
<img width="850" alt="image" src="https://github.com/rbardini/storybook-addon-paddings/assets/6528584/09d9caf5-1a06-4acb-ab48-07851d890175">

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-ui-and-props-for-button-and-iconbutton-components

**Comment by DanAnton** [comment]
Do you have any updates on this issue? I also don't see the icon after latest update, is there any workaround?

**Comment by awreese** [comment]
When attempting to integrate this addon in SB8 my stories fail to build and load the preview.
