### ISSUE TITLE
Compatibility with HTML framework?

### ISSUE THREAD

**Issue by tylersticka** [rbardini/storybook-addon-paddings#6]
After installing this add-on and configuring the `paddings` parameter, every component displays this error in the Storybook UI:

<img width="854" alt="Screen Shot 2020-03-25 at 5 03 23 PM" src="https://user-images.githubusercontent.com/69633/77596947-a508a100-6eba-11ea-861d-14b4fb61664d.png">

I originally thought this might be the same issue as #5, but decided to create a new issue since the error messages differ.

**Comment by rbardini** [comment]
Hi @tylersticka! Yes, I think they might be related. Haven't had time to look into this yet, but will try to work on a fix ASAP 👍
