### ISSUE TITLE
Use paddings config object instead of array

### ISSUE THREAD

**Issue by rbardini** [rbardini/storybook-addon-paddings#8]
The addon uses an array to define padding options, similar to the [backgrounds addon](https://github.com/storybookjs/storybook/tree/master/addons/backgrounds). This makes it difficult to merge global configurations to story overrides, forcing the redefinition of global values in stories.

To avoid this issue, the addon should use a config object (map) instead, like the [viewport addon](https://github.com/storybookjs/storybook/tree/master/addons/viewport):

```js
addParameters({
  paddings: {
    paddings: {
      small: { name: 'Small', value: '16px' },
      medium: { name: 'Medium', value: '32px' },
      largin: { name: 'Large', value: '64px' },
    },
    defaultPadding: 'medium',
  },
});
```

**Comment by joanrm20** [comment]
hey @rbardini, can I try to tackle this one?

**Comment by rbardini** [comment]
@joanrm20 sure 🙂
